#!/usr/bin/env python3
# flattencom - Rust Translation Macro Generator
#
# Generates literal checked format branches from the Chinese message catalog.
#
# Authors:
# worryzu <worryzu@gmail.com> @LinearTeam
#
# Copyright (C) 2026 Evarentha
# SPDX-License-Identifier: GPL-3.0-or-later

"""Generate checked, literal Rust format branches from the translation catalog."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
catalog=json.loads((root/'crates/flattencom-core/locales/zh-CN.json').read_text(encoding='utf-8'))
lines=['// Generated by scripts/gen-messages.py; do not edit.', '/// Format a localized application message.', '#[macro_export]', 'macro_rules! tr {']
from importlib.util import spec_from_file_location, module_from_spec
spec=spec_from_file_location('file_headers',root/'scripts/maintain-headers.py')
headers=module_from_spec(spec);spec.loader.exec_module(headers)
lines.insert(0,headers.header_for('crates/flattencom-core/src/messages.rs').rstrip('\n')+'\n')
for en,zh in sorted(catalog.items()):
    en=json.dumps(en,ensure_ascii=False);zh=json.dumps(zh,ensure_ascii=False)
    lines.append(f'({en} $(, $($args:tt)*)?) => {{ if $crate::i18n::language() == $crate::i18n::Language::Chinese {{ format!({zh} $(, $($args)*)?) }} else {{ format!({en} $(, $($args)*)?) }} }};')
lines+=['($message:literal $(, $($args:tt)*)?) => { format!($message $(, $($args)*)?) };','}']
(root/'crates/flattencom-core/src/messages.rs').write_text('\n'.join(lines)+'\n',encoding='utf-8')
